### ISSUE TITLE
Convert LSSTErrorModel to PhotErr

### ISSUE THREAD

**Issue by jfcrenshaw** [LSSTDESC/rail_astro_tools#3]
I wrote a standalone package for the error model called [PhotErr](https://github.com/jfcrenshaw/photerr). I will work on converting the RAIL error model to a PhotErr implementation. It will just be a thin wrapper around `photerr.LsstErrorModel`.

**Comment by aimalz** [comment]
@hangqianjun has brought up that, while [this is already implemented in this repository](https://github.com/LSSTDESC/rail_astro_tools/blob/11ee32960bf048cfa8c6cc90461f4079089af3f2/src/rail/creation/degradation/observing_condition_degrader.py#L10), it's not clear whether it needs to be updated elsewhere and/or if it belongs in a different repo because it only requires pandas.

**Comment by jfcrenshaw** [comment]
That is just inside the observing conditions degrader which applies the error model using a map. But we also want a simple error model degrader that can just be applied to a table
